---
- name: Install the required php packages
  yum: name={{ item }} state=present enablerepo=remi
  with_items:
    - php-mcrypt
    - php-pdo
    - php-mysql
    - php-sqlite
    - php-pgsql
    - php-gd
    - php-mbstring
    - php-phpunit-PHPUnit

- name: Download composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/bin/composer.phar

- name: Set composer permissions
  file: path=/usr/bin/composer.phar mode=0755
